---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: "node1"
      prompt: "Enter the name for the first node"
      private: false
    - name: "node2"
      prompt: "Enter the name for the second node"
      private: false
    - name: "node3"
      prompt: "Enter the name for the third node"
      private: false
  tasks:
    - name: Launch node1
      command: "multipass launch --name {{ node1 }} --cpus 2 --mem 2G --disk 30G lts"
    - name: Launch node2
      command: "multipass launch --name {{ node2 }} --cpus 2 --mem 2G --disk 30G lts"
    - name: Launch node3
      command: "multipass launch --name {{ node3 }} --cpus 2 --mem 2G --disk 30G lts"