- name: Install K3s Master and Get Token
  hosts: master
  become: true
  tasks:
    - name: K3S Master
      when: inventory_hostname in groups['master']
      block:
        - name: Check K3s Service Status
          ansible.builtin.command: systemctl status k3s.service
          register: k3s_master_status
          ignore_errors: true

        - name: Install K3s Master Node
          ansible.builtin.shell:
            cmd: curl -fsSL https://get.k3s.io | sh -
            timeout: 600
          when: k3s_status.rc != 0

        - name: Wait for Token File
          ansible.builtin.wait_for:
            path: /var/lib/rancher/k3s/server/node-token
            state: present

        - name: Get K3s Token
          ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
          register: k3s_token
        
        - name: Gather Master fact 
          debug:
            msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
          register: master_ip
    - name: Install K3S Worker
      when: inventory_hostname in groups['worker']
      block:
        - name: Check if K3s is running on worker
          ansible.builtin.command: systemctl status k3s.service
          register: k3s_worker_status
          ignore_errors: true
        - name: Setup worker nodes
          ansible.builtin.shell:
            cmd: curl -sfL https://get.k3s.io | \
            INSTALL_K3S_EXEC="agent" \
            K3S_URL="https://{{ groups['master'][0] }}:6443" \
            K3S_TOKEN="{{ k3s_token }}" \
            sh -

    # - name: Show Token
    #   debug:
    #     msg: "{{ k3s_token.stdout }}"