- name: Install K3s Master and Get Token
  hosts: kubernetes
  become: true
  gather_facts: true  # Ensure facts are gathered for network info

  tasks:
    - name: Install K3S Master
      when: inventory_hostname in groups['master']
      block:
        - name: Check K3s Service Status
          ansible.builtin.command: systemctl status k3s.service
          register: k3s_master_status
          ignore_errors: true

        - name: Install K3s Master Node
          ansible.builtin.shell: curl -fsSL https://get.k3s.io | sh -
          when: k3s_master_status.rc != 0

        - name: Wait for Token File
          ansible.builtin.wait_for:
            path: /var/lib/rancher/k3s/server/node-token
            state: present

        - name: Get K3s Token
          ansible.builtin.command: cat /var/lib/rancher/k3s/server/node-token
          register: k3s_token

        - name: Set Master IP Fact
          set_fact:
            master_ip: "{{ ansible_default_ipv4.address }}"
      
        - name: Store K3s Token Globally
          set_fact:
            k3s_token_value: "{{ k3s_token.stdout }}"
          delegate_to: localhost
          run_once: true

    - name: Ensure K3s Token is Available to Workers
      set_fact:
        k3s_token: "{{ hostvars[groups['master'][0]]['k3s_token_value'] }}"
        master_ip: "{{ hostvars[groups['master'][0]]['master_ip'] }}"
      when: inventory_hostname in groups['worker']

    - name: Install K3S Worker
      when: inventory_hostname in groups['worker']
      block:
        - name: Check if K3s is running on worker
          ansible.builtin.command: systemctl status k3s.service
          register: k3s_worker_status
          ignore_errors: true

        - name: Setup Worker Nodes
          ansible.builtin.shell: >-
            curl -sfL https://get.k3s.io |
            INSTALL_K3S_EXEC="agent"
            K3S_TOKEN={{ k3s_token }}
            sh -s - --server https://{{ master_ip }}:6443
          when: k3s_worker_status.rc != 0

    - name: Confirm Nodes (Only on Master)
      when: inventory_hostname in groups['master']
      block:
        - name: Get Cluster Nodes
          ansible.builtin.command: kubectl get nodes
          register: nodes_status
          changed_when: false

        - name: Show Cluster Nodes
          debug:
            msg: "{{ nodes_status.stdout_lines }}"