- name: Install K3s Cluster
  hosts: "{{ target_hosts }}"
  become: true
  vars_prompt:
    - name: "target_hosts"
      prompt: "Which hosts"
      private: false

  tasks:
    - name: Install K3s Master
      when: inventory_hostname in groups['master']
      block:
        - name: Check K3s Service Status on Master
          ansible.builtin.command: systemctl status k3s.service
          register: k3s_status
          ignore_errors: true

        - name: Install K3s Master Node
          ansible.builtin.shell: curl -fsSL https://get.k3s.io | sh -
          when: k3s_status.rc != 0

        - name: Get K3s Token
          ansible.builtin.slurp:
            src: /var/lib/rancher/k3s/server/token
          register: k3s_token
          when: k3s_status.rc != 0

    - name: Install K3s Worker
      when: inventory_hostname in groups['worker']
      block:
        - name: Check K3s Service Status on Worker
          ansible.builtin.command: systemctl status k3s-agent.service
          register: k3s_worker_status
          ignore_errors: true

        - name: Install K3s Worker Node
          ansible.builtin.shell: >-
            curl -fsSL https://get.k3s.io |
            K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443
            K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token']['content'] | b64decode }}
            sh -
          when: k3s_worker_status.rc != 0

    - name: Set Kubectl Permissions
      ansible.builtin.command: chmod 755 /usr/local/bin/kubectl
