---
- name: docker
  hosts: pi
  become: true
  gather_facts: no
  vars_prompt:
    - name: "docker_user"
      prompt: "Enter the user to give docker permissions to"
      private: no
  tasks:
    - name: Install docker.io
      apt: name=docker.io state=present update_cache=no

    - name: Install docker-compose
      apt: name=docker-compose state=present update_cache=no

    - name: Grant perm
      ansible.builtin.command: usermod -aG docker {{  docker_user }}

    - name: Start docker
      ansible.builtin.command: systemctl enable --now docker
