- name: Lynis
  hosts: node3
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Download lynis
      ansible.builtin.get_url:
        url: https://downloads.cisofy.com/lynis/lynis-3.0.9.tar.gz
        dest: /opt/
        mode: '0755'
    - name: Extract lynis
      ansible.builtin.command:
        cmd: tar xzf /opt/lynis-3.0.9.tar.gz -C /opt
    - name: Move files
      ansible.builtin.command:
        cmd: mv /opt/lynis /usr/local/
    - name: Link files
      ansible.builtin.file:
        src: /usr/local/lynis/lynis
        dest: /usr/local/bin/lynis
        state: link