---
- name: Tailscale installation
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if Tailscale exists
      command: which tailscale
      register: tailscale_exists
      ignore_errors: true

    - name: Download Tailscale install script
      get_url:
      url: https://tailscale.com/install.sh
      dest: /tmp/install.sh
      mode: '0755'

    - name: Run Tailscale install script
      command: sh /tmp/install.sh
      when: tailscale_exists.rc != 0