---
- name: Tailscale installation
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if Tailscale exists
      command: which tailscale
      register: tailscale_exists
      ignore_errors: true

    - name: Download and install Tailscale
      shell: curl -fsSL https://tailscale.com/install.sh | sh
      when: tailscale_exists.rc != 0