---
- name: Install Docker and Docker-Compose-V2
  hosts: "{{ target_hosts }}"
  become: true  # Run tasks with sudo privileges
  vars_prompt:
    - name: "target_hosts"
      prompt: "which hosts"
      private: false
    - name: "docker_user"
      prompt: "which user"
      private: false
  tasks:
    # --- Ubuntu/Debian ---
    - name: Install docker (Ubuntu/Debian)
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: true  # Update the package cache before installing
      when: ansible_os_family == "Debian"

    # --- Alpine ---
    - name: Install Docker (Alpine)
      ansible.builtin.apk:
        name:
          - docker
          - docker-compose
        state: present
        update_cache: true  # Update the package cache before installing
      when: ansible_os_family == "Alpine"

    - name: Enable and start Docker service
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started

    - name: Add the current user to the Docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        groups: docker
        append: true  # Append the user to the Docker group without removing existing groups
