---
- name: Install Docker and set up a Docker Swarm cluster
  hosts: swarm
  become: yes
  vars:
    docker_apt_key_url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    docker_apt_repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    swarm_manager: "{{ groups['manager'][0] }}"
    manager_token: ""
    worker_token: ""

  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: "{{ docker_apt_key_url }}"
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "{{ docker_apt_repo }}"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker-ce
        state: latest

    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

- name: Initialize Docker Swarm on the manager node
  hosts: manager
  become: yes
  tasks:
    - name: Initialize Docker Swarm
      ansible.builtin.command:
        cmd: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
      when: manager_token == ""

    - name: Get manager join-token
      ansible.builtin.command:
        cmd: docker swarm join-token -q manager
      register: manager_token_output
      when: manager_token == ""

    - name: Set manager token
      set_fact:
        manager_token: "{{ manager_token_output.stdout }}"
      when: manager_token == ""

    - name: Get worker join-token
      ansible.builtin.command:
        cmd: docker swarm join-token -q worker
      register: worker_token_output
      when: worker_token == ""

    - name: Set worker token
      set_fact:
        worker_token: "{{ worker_token_output.stdout }}"
      when: worker_token == ""

- name: Join worker nodes to the Docker Swarm cluster
  hosts: workers
  become: yes
  tasks:
    - name: Join the swarm as a worker
      ansible.builtin.command:
        cmd: docker swarm join --token {{ hostvars[swarm_manager].worker_token }} {{ hostvars[swarm_manager].ansible_default_ipv4.address }}:2377
      when: worker_token != ""

- name: Display Docker Swarm status
  hosts: manager
  become: yes
  tasks:
    - name: Display Swarm join status
      ansible.builtin.command:
        cmd: docker node ls
      register: swarm_status

    - name: Show Swarm status
      ansible.builtin.debug:
        msg: "{{ swarm_status.stdout }}"
