---
- name: Define static hosts and user
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Add manager host to inventory group
      add_host:
        name: "node1"  # Replace with the actual manager host
        groups: manager

    - name: Add worker hosts to inventory group
      add_host:
        name: "{{ item }}"
        groups: workers
      loop:
        - "node2"  # Replace with actual worker hostnames
        - "node3"  # Add more worker hosts as needed

- name: Install Docker and Setup Swarm Manager
  hosts: manager
  become: true
  gather_facts: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: true
      when: docker_installed.rc != 0

    - name: Add user to the docker group
      user:
        name: "root"  # Replace with the actual username
        groups: docker
        append: true

    - name: Get manager IP address for wlan0
      set_fact:
        advertise_addr: "{{ ansible_facts['interfaces']['wlan0']['ipv4']['address'] }}"

    - name: Initialize Docker Swarm with specified advertise address
      command: docker swarm init --advertise-addr {{ advertise_addr }}
      register: swarm_init
      when: docker_installed.rc == 0

    - name: Get Join Token for Workers
      command: docker swarm join-token -q worker
      register: worker_join_token
      when: swarm_init.changed

    - name: Set fact with manager IP and token
      set_fact:
        manager_ip: "{{ advertise_addr }}"
        worker_token: "{{ worker_join_token.stdout }}"
      when: swarm_init.changed

- name: Setup Swarm Workers
  hosts: workers
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: true

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present
        update_cache: true
      when: docker_installed.rc != 0

    - name: Add user to the docker group
      user:
        name: "root"  # Replace with the actual username
        groups: docker
        append: true

    - name: Join Docker Swarm as Worker
      command: docker swarm join --token {{ hostvars['manager']['worker_token'] }} {{ hostvars['manager']['manager_ip'] }}:2377
      when: docker_installed.rc == 0
