---
- name: Install and configure Docker and Docker Compose
  hosts: "{{ target_hosts }}"
  become: yes  # Run tasks with sudo privileges
  vars_prompt:
    - name: "target_hosts"
      prompt: "which hosts"
      private: false
    - name: "docker_user"
      prompt: "which user"
      private: false
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes  # Update the package cache before installing

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add the current user to the Docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes  # Append the user to the Docker group without removing existing groups