---
- name: Install Docker and Docker Compose on Ubuntu
  hosts: "{{  target_hosts }}"
  become: yes
  gather_facts: false
  vars_prompt:
    - name: "docker_user"
      prompt: "Grant privileges to docker user"
      private: false
    - name: "target_hosts"
      prompt: "which hosts"
      private: false
  tasks:
    - name: Update apt package cache and install dependencies
      apt:
        update_cache: yes
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    # - name: Add Docker's official GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker APT repository
    #   apt_repository:
    #     repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    #     state: present

    - name: Update apt and install Docker
      apt:
        update_cache: no
        name: docker.io
        state: present
        
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Ensure Docker service is enabled and running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add a user to the docker group
      user:
        name: "{{ docker_user }}"
        groups: docker
        append: yes
