---
- name: Deploy 3 multipass nodes
  hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: "node1"
      prompt: "Enter the name for the first node"
      private: false
    - name: "node2"
      prompt: "Enter the name for the second node"
      private: false
    - name: "node3"
      prompt: "Enter the name for the third node"
      private: false
    - name: "ssh_key"
      prompt: "Enter your ssh key"
      private: false
    - name: "mem"
      prompt: "How much memory"
      private: false
    - name: "cpu"
      prompt: "How many cores"
      private: false
    - name: "disk"
      prompt: "Enter disk size"
      private: false
  tasks:
    - name: Launch node1
      command: "multipass launch --name {{ node1 }} --cpus {{ cpu }} --mem {{ mem }} --disk {{ disk }} lts"
    - name: Launch node2
      command: "multipass launch --name {{ node2 }} --cpus {{ cpu }} --mem {{ mem }} --disk {{ disk }} lts"
    - name: Launch node3
      command: "multipass launch --name {{ node3 }} --cpus {{ cpu }} --mem {{ mem }} --disk {{ disk }} lts"
    - name: Copy SSH key to node1
      command: "multipass exec {{ node1 }} -- sh -c 'echo {{ ssh_key }} >> /home/ubuntu/.ssh/authorized_keys'"
    - name: Copy SSH key to node2
      command: "multipass exec {{ node2 }} -- sh -c 'echo {{ ssh_key }} >> /home/ubuntu/.ssh/authorized_keys'"
    - name: Copy SSH key to node3
      command: "multipass exec {{ node3 }} -- sh -c 'echo {{ ssh_key }} >> /home/ubuntu/.ssh/authorized_keys'"
