---
- name: Multipass launcher
  hosts: localhost
  gather_facts: false
  become: false
  connection: local
  vars_prompt:
    - name: "nodes"
      prompt: "How many nodes do you want to create?"
      private: false
    - name: "node_name"
      prompt: "Node name prefix? example mynode"
      private: false
    - name: "mem"
      prompt: "How much memory? example 4G"
      private: false
    - name: "cpu"
      prompt: "How many cores? example 2"
      private: false
    - name: "disk"
      prompt: "Disk size example 40G"
      private: false
    - name: "network"
      prompt: "Network name example default"
      private: false
    - name: "image"
      prompt: "Image example lts"
      private: false

  tasks:
    - name: Launch {{ nodes }} instances
      ansible.builtin.command: >
        multipass launch --name {{ node_name }}{{ item }}
        --cpus {{ cpu }}
        --memory {{ mem }}
        --disk {{ disk }}
        --network name={{ network }},mode=manual
        {{ image }}
      with_sequence: start=1 end="{{ nodes }}"