---
- name: Multipass launcher
  hosts: localhost
  gather_facts: False
  vars_prompt:
    - name: "nodes"
      prompt: "How many Falsedes do you want to create?"
      private: false
    - name: "mem"
      prompt: "How much memory? example 4G"
      private: false
    - name: "cpu"
      prompt: "How many cores? example 2"
      private: false
    - name: "disk"
      prompt: "enter disk size example 40G"
    - name: "image"
      prompt: "which image? example lts"
      private: false


  tasks:
    - name: Launch {{ nodes }} instances
      ansible.builtin.command: multipass launch --name node{{ item }} --cpus {{ cpu }} --memory {{ mem }} --disk {{ disk }} {{ image }}
      with_sequence: start=1 end="{{ nodes }}"