---
- hosts: localhost
  gather_facts: No
  vars_prompt:
    - name: "nodes"
      prompt: "How many nodes do you want to create?"
      private: no
    - name: "mem"
      prompt: "How much memory? example 4G"
      private: no
    - name: "cpu"
      prompt: "How many cores? example 2"
      private: no
    - name: "disk"
      prompt: "enter disk size example 40G"
    - name: "image"
      prompt: "which image? example lts"
      private: no


  tasks:
    - name: Launch instances
      command: multipass launch --name node{{ item }} --cpus {{ cpu }} --memory {{ mem }} --disk {{ disk }} {{ image }}
      with_sequence: start=1 end="{{ nodes }}"