---
- name: Update macOS machine
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check if Homebrew is installed
      ansible.builtin.command: which brew
      register: brew_installed
      ignore_errors: true

    - name: Install Homebrew
      ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when: brew_installed.rc != 0

    - name: Update Homebrew
      ansible.builtin.command: brew update

    - name: Upgrade Homebrew packages
      ansible.builtin.command: brew upgrade

    - name: Check for system updates
      ansible.builtin.command: softwareupdate -l

    - name: Check if pip-review is installed
      ansible.builtin.command: which pip-review
      register: pip_review_installed
      ignore_errors: true

    - name: Install pip-review if not installed
      ansible.builtin.command: pip install --upgrade pip-review
      when: pip_review_installed.rc != 0

    - name: Upgrade python packages
      ansible.builtin.command: pip-review --auto