---
- name: Modify sudoers file
  hosts: all
  become: true
  tasks:
   - name: Update sudoers file
     ansible.builtin.lineinfile:
      path: /etc/sudoers
      line: '%sudo ALL=(ALL) NOPASSWD: ALL'
      state: present
      validate: 'visudo -cf %s'
