- hosts: multipass
  remote_user: ubuntu
  become: true
  tasks:
    - name: update and upgrade apt caches
      apt:
        update_cache: yes
        upgrade: yes
    - name: install zsh 
      apt:
        name: zsh
        state: latest
    - name: change user shell to zsh 
      user:
        name: "ubuntu"
        shell: /bin/zsh
    - name: install git
      apt:
        name: git
        state: latest
    - name: Install oh-my-zsh
      shell:
        cmd: "curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh"
    
          #    - name: replace default oh-my-zsh dir
          #      copy:
          #        src: .oh-my-zsh
          #        dest: /home/ubuntu/
          #        owner: ubuntu
          #        group: ubuntu
          #        mode: '0755'
          #        force: yes

    - name: replace default .zshrc
      copy:
        src: .zshrc
        dest: /home/ubunt
        owner: ubuntu
        group: ubuntu
        mode: '0644'
        force: yes

