---
- name: Update Tailscale
  hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: false
  vars_prompt:
    - name: "target_hosts"
      prompt: "which hosts"
      private: false
  tasks:
    - name: Update tailscale package
      ansible.builtin.apt:
        name: tailscale
        state: latest
    - name: Restart tailscale service
      ansible.builtin.systemd:
        name: tailscaled
        state: restarted
    - name: Verify Tailscale version
      ansible.builtin.command:
        cmd: tailscale version
      register: tailscale_version_output
    - name: Display Tailscale version
      ansible.builtin.debug:
        msg: "Tailscale version: {{ tailscale_version_output.stdout }}"
