- name: weekly patches
  hosts: pi
  become: true
  become_method: doas
  tasks:
    - name: Ensure alpine-conf is installed (for setup-apkrepos)
      ansible.builtin.apk:
        name: alpine-conf
        state: present
        update_cache: yes
      when: ansible_os_family == "Alpine"

    - name: Update to fastest mirror (Alpine)
      ansible.builtin.command: setup-apkrepos -f
      when: ansible_os_family == "Alpine"

    - name: Upgrade all packages (Alpine)
      ansible.builtin.apk:
        upgrade: yes
      when: ansible_os_family == "Alpine"