- name: Weekly Patches
  hosts: localhost
  connection: localhost
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Update APT Cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Upgrade APT packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true

    - name: Check if system requires a reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot
      ansible.builtin.reboot:
        msg: "Rebooting.."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists
