---
- name: Weekly patches
  hosts: all
  become: true
  gather_facts: true
  tasks:
      # --- Ubuntu/Debian ---
    - name: Update cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400
      when: ansible_os_family == "Debian"

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: true
        autoremove: true
        autoclean: true
      register: apt_upgrade_output
      when: ansible_os_family == "Debian"

    # --- RHEL ---
    - name: Update and upgrade all packages
      ansible.builtin.yum:
        name: '*'
        state: present
      when: ansible_os_family == "RedHat"

    # --- Alpine ---
    - name: Upgrade all packages
      ansible.builtin.apk:
        upgrade: true
      when: ansible_os_family == "Alpine"

    # --- reboot if required ---
    - name: Check if system requires a reboot
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Display variable
      ansible.builtin.debug:
        msg: '{{ reboot_required_file.stat.exists }}'

    - name: Reboot
      ansible.builtin.reboot:
        msg: "Rebooting.."
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists