- hosts: all
  become: true
  become_user: root
  tasks:
    - name: Upgrade apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: Upgrade packages
      apt:
        upgrade: yes
        update_cache: yes
